on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.1.2
    - name: install node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: pnpm install --frozen-lockfile
      run: pnpm install --frozen-lockfile
    - name: primsa generate
      run: primsa generate
    - name: tsc
      uses: icrawl/action-tsc@v1
      with:
        project: './src'